### ISSUE TITLE
Weighted Cosine Similarity

### ISSUE THREAD

**Issue by dalekube** [vh-d/RPortfolioSimilarity#1]
Consider the code chunk below. In theory, a weighted cosine similarity formula would include the weight in the numerator to reduce the scalar product. I can't find any documentation to explain the current formula that incorporates weights. The current output of 'wtVCosSimilarity' does not match.

Please provide clarification or explicitly list the weighted formula.

```
x = c(1,2,3)
y = c(1,5,12)
w = c(0.5,1,1)

# Function result = 0.9720782
wtVCosSimilarity(x,y,w)

# Weighting the scalar product in the numerator
# Result = 0.9531571
sum(x*y*w)/(sqrt(sum(x^2))*sqrt(sum(y^2)))
```

**Comment by dalekube** [comment]
After testing a couple alternatives, I figured out that the weighted cosine similarity function is using the following formula (matching this example):

`sum(x*y*w)/(sqrt(sum(x^2*w))*sqrt(sum(y^2*w)))`

This includes the weights in the denominator, multiplying each vector value, raised to the second power, by the corresponding weight.

**Comment by dalekube** [comment]
It would be great if the formulas are explicitly listed in the docs!

**Comment by vh-d** [comment]
> After testing a couple alternatives, I figured out that the weighted cosine similarity function is using the following formula (matching this example):
> 
> `sum(x*y*w)/(sqrt(sum(x^2*w))*sqrt(sum(y^2*w)))`
> 
> This includes the weights in the denominator, multiplying each vector value, raised to the second power, by the corresponding weight.

Yep, thanks, a look in the source code confirms that: 

```
double wtVCosSimilarity(NumericVector a, NumericVector b, NumericVector w) {
  double sA, sB, sI;

  sA = sum(w*a*a);
  sB = sum(w*b*b);
  sI = sum(w*a*b);
  return (sI/sqrt(sA * sB));
}
```

I will put in the docs.

**Comment by dalekube** [comment]
Great, thanks for confirming the formula. Do you have a link to an external source that helps to confirm this formula? It makes sense as I experiment with it, but a general online search does not return any robust use cases or studies that help with validation.

**Comment by vh-d** [comment]
Closed in [8a4094d](https://github.com/vh-d/RPortfolioSimilarity/commit/8a4094d2457e2e22d5aa451a547e177566092da2)

**Comment by vh-d** [comment]
I am not aware of any solid reference right now. It has been some time since I wrote this part of my dissertation. But I think this was the only formula that behaved well (a.k.a. met some basic requirements on edge cases, equal weights etc...).

**Comment by vh-d** [comment]
[this link](https://itl.nist.gov/div898/software/dataplot/refman2/auxillar/weigcorr.htm) may help
